version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - provibackend
    networks:
        - provi

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /home/ccvis/data/mongo:/data/db
    networks:
        - provi
    ports:
      - "27017:27017"

  provibackend:
    image: provibackend:latest
    container_name: provibackend
    ports:
      - "1234:80"  # Map container port 8080 to host port 8080 (adjust as needed)
    env_file:
      - .env
    volumes:
      - /home/ccvis/data/provibackend:/code/ProViBackend/output/
    networks:
        - provi
    depends_on:
      - redis
      - mongo

  redis:
    build:
        context: ./redis
        dockerfile: Dockerfile
    container_name: redis
    restart: always
    volumes:
      - /home/ccvis/data/redis:/data
    ports:
      - "6379"
    networks:
        - provi


volumes:
  output:

networks:
  provi:
    driver: bridge