server {
    listen 80;
    server_name cc-vis.rz.uni-mannheim.de www.cc-vis.rz.uni-mannheim.de;

    # Redirect HTTP to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name cc-vis.rz.uni-mannheim.de www.cc-vis.rz.uni-mannheim.de;

    # SSL configuration
    ssl_certificate /etc/letsencrypt/live/cc-vis.rz.uni-mannheim.de/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cc-vis.rz.uni-mannheim.de/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Increase the accepted upload file size
    client_max_body_size 300M;

    # Reverse proxy for frontend
    location / {
        proxy_pass http://provifrontend:3000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Reverse proxy for backend
    location /api/ {
        proxy_pass http://provibackend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        # Cookie forwarding between frontend and backend
        proxy_cookie_domain backend cc-vis.rz.uni-mannheim.de;
        proxy_cookie_path / /;
    }
}