name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Write .env
        env:
          SECRET_ENV: ${{ secrets.SECRET_ENV }}
        run: echo "$SECRET_ENV" > .env

      - name: Remove any pre-compose containers
        run: docker rm -f redis mongo provibackend provifrontend nginx 2>/dev/null || true

      - name: Deploy
        run: docker compose up -d --build
